In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("ch1_enrollment.csv")

df.head()

   Year  Bachelors  Masters  MBA  MsTax  PhD
0  1994        190       10    3      6    1
1  1995        193       10    4      6    1
2  1996        174        9    3      5    1
3  1997        174        9    3      5    1
4  1998        174        9    3      5    1

In [9]:
df.iloc[1]

Year         1995
Bachelors     193
Masters        10
MBA             4
MsTax           6
PhD             1
Name: 1, dtype: int64

In [10]:
df.iloc(1)

In [11]:
df.iloc[[1,2]]

   Year  Bachelors  Masters  MBA  MsTax  PhD
1  1995        193       10    4      6    1
2  1996        174        9    3      5    1

In [15]:
df.iloc[[1,3],[1,3]]

   Bachelors  MBA
1        193    4
3        174    3

In [21]:
df.groupby("Year").mean()

      Bachelors  Masters  MBA  MsTax  PhD
Year
1994      190.0     10.0  3.0    6.0  1.0
1995      193.0     10.0  4.0    6.0  1.0
1996      174.0      9.0  3.0    5.0  1.0
1997      174.0      9.0  3.0    5.0  1.0
1998      174.0      9.0  3.0    5.0  1.0
1999      134.0      9.0  4.0    3.0  1.0
2000      128.0      9.0  2.0    3.0  1.0
2001      135.0     10.0  4.0    2.0  1.0
2002      133.0     13.0  4.0    4.0  1.0
2003      141.0     18.0  5.0    4.0  1.0
2004      143.0     19.0  4.0    4.0  1.0
2005      143.0     19.0  4.0    4.0  1.0
2006      143.0     19.0  4.0    4.0  1.0
2007      173.0     21.0  5.0    3.0  1.0
2008      181.0     24.0  4.0    2.0  1.0
2009      181.0     24.0  4.0    2.0  1.0
2010      188.0     29.0  5.0    3.0  1.0
2011      188.0     29.0  5.0    3.0  1.0
2012      212.0     30.0  5.0    3.0  1.0
2013      212.0     30.0  5.0    3.0  1.0
2014      212.0     30.0  5.0    3.0  1.0
2015      217.0     40.0  3.0    2.0  1.0
2016      216.0     29.0  3.0    3.0  1.0
2017      216.0     29.0  3.0    3.0  1.0